name: Generate README from manual

on:
  push:
    branches: [ master ]
    paths: 
      - mb.1
      - .github/**

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate README
        run: groff -man -Tascii mb.1 > README
      
      - uses: EndBug/add-and-commit@v4
        with:
          add: README
          message: Auto generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
